### ISSUE TITLE
Minor typo and broken link in 1-Computer Architecture

### ISSUE THREAD

**Issue by return0927** [shiftpsh/sgcs-cse3030#1]
1. Broken img link [week1 - Introduction#binary-numbers](https://github.com/shiftpsh/sgcs-cse3030/blob/master/notes/1%20-%20Computer%20Architecture/week1%20-%20Introduction.md#binary-numbers)
This seems that "Android Meme" image file is not commited. (Maybe expected [this](https://scontent-icn1-1.xx.fbcdn.net/v/t1.0-9/fr/cp0/e15/q65/375478_10150507661549522_483829322_n.jpg?_nc_cat=101&efg=eyJpIjoidCJ9&_nc_oc=AQn4ZFARsTecFfFxe_VyPhV3oqkr-4hioeEJkykIC6G5e4kDoz_pJZdbZEcRaM6Q1Pg&_nc_ht=scontent-icn1-1.xx&tp=1&oh=b3a8b5f72e02630ea67aa8ba078b9da5&oe=5E360574)?)

1. Typo [week2.1 - Digital Circuits#Register](https://github.com/shiftpsh/sgcs-cse3030/blob/master/notes/1%20-%20Computer%20Architecture/week2.1%20-%20Digital%20Circuits.md#register)
```diff
- ... D랑 Q는 각각 m개 비트로 이루어져 있가
+ ... D랑 Q는 각각 m개 비트로 이루어져 있다
```

**Comment by shiftpsh** [comment]
Fixed.
